# Generated by Django 2.2.5 on 2021-02-04 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=80, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=80, null=True, verbose_name='Last Name')),
                ('phone_number', models.IntegerField(null=True, verbose_name='Phone Number')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='Country')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last Login')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XpayAccount',
            fields=[
                ('currency', models.CharField(max_length=100)),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('iban_no', models.CharField(max_length=100)),
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('account_number2', models.CharField(max_length=50)),
                ('account_status', models.CharField(default='open', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_iban_no', models.CharField(max_length=80)),
                ('sender_full_name', models.CharField(max_length=80)),
                ('receiver_iban_no', models.CharField(max_length=80)),
                ('xpay_iban_no', models.CharField(max_length=80)),
                ('date_of_transaction', models.DateTimeField(auto_now_add=True, null=True)),
                ('receiver_full_name', models.CharField(max_length=80)),
                ('receiver_bank_name', models.CharField(max_length=80)),
                ('sender_bank_name', models.CharField(max_length=80)),
                ('account_balance', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('xpayaccount_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpay.XpayAccount')),
            ],
        ),
    ]
